# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-12-04 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicio', models.DateField()),
                ('dia_fim', models.DateField()),
                ('moeda', models.CharField(max_length=255)),
            ],
        ),
    ]
